apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc2
  labels:
    app: rabbitmq-app
spec:
  type: LoadBalancer
  ports:
  - port: 15672
    targetPort: 15672
  selector:
    app: rabbitmq-app